# Generated by Django 5.2.6 on 2025-09-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0004_alter_proovedores_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasillo',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pasillo',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
