# Generated by Django 5.2.6 on 2025-09-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0005_pasillo_disponible_pasillo_estado_planta_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasillo',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='planta',
            name='disponible',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
