# Generated by Django 5.2.6 on 2025-10-02 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0007_pasillo_plnata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasillo',
            old_name='plnata',
            new_name='planta',
        ),
    ]
