# Generated by Django 5.2.6 on 2025-10-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0009_planta_catidad_maxima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planta',
            name='catidad_maxima',
        ),
    ]
