# Generated by Django 5.2.6 on 2025-10-02 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0010_remove_planta_catidad_maxima'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasillo',
            name='planta',
        ),
        migrations.AddField(
            model_name='planta',
            name='pasillo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genstionalmacen.planta'),
        ),
    ]
