# Generated by Django 5.2.6 on 2025-10-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0013_planta_secciones_maximas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasillo',
            name='secciones_maximas',
            field=models.IntegerField(default=3),
        ),
    ]
