# Generated by Django 5.2.6 on 2025-10-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0016_alter_planta_secciones_maximas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasillo',
            name='secciones_maximas',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='planta',
            name='secciones_maximas',
            field=models.IntegerField(default=50),
        ),
    ]
