# Generated by Django 5.2.6 on 2025-10-03 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0017_alter_pasillo_secciones_maximas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=200)),
                ('disponible', models.BooleanField(default=True)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genstionalmacen.planta')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genstionalmacen.proovedores')),
            ],
        ),
    ]
