# Generated by Django 5.2.6 on 2025-10-03 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0018_contenedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contenedor',
            new_name='secciones',
        ),
    ]
