# Generated by Django 5.2.6 on 2025-10-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0019_rename_contenedor_secciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secciones',
            name='codigo',
            field=models.CharField(max_length=200),
        ),
    ]
