# Generated by Django 5.2.6 on 2025-10-06 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0024_merge_0002_rename_models_0023_auto_20251006_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secciones1',
            old_name='planta',
            new_name='nivel',
        ),
        migrations.RenameField(
            model_name='ubicaciones',
            old_name='planta',
            new_name='nivel',
        ),
        migrations.RenameField(
            model_name='ubicaciones',
            old_name='pasillo',
            new_name='rack',
        ),
        migrations.RemoveField(
            model_name='niveles',
            name='pasillo',
        ),
        migrations.AddField(
            model_name='niveles',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='genstionalmacen.racks'),
        ),
    ]
