# Generated by Django 5.2.6 on 2025-10-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0027_seguimiento_ubicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='seguimiento',
        ),
    ]
