# Generated by Django 5.2.7 on 2025-11-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0028_delete_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
