# Generated by Django 5.2.6 on 2025-09-15 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pasillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='proovedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('telefono', models.TextField(max_length=200)),
                ('correo', models.TextField(max_length=200)),
                ('direccion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200, unique=True)),
                ('descripcion_palet', models.TextField(max_length=200)),
                ('pasillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genstionalmacen.pasillo')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genstionalmacen.planta')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genstionalmacen.proovedores')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
