# Generated by Django 5.2.6 on 2025-09-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0002_pasillo_planta_proovedores_ubicacion_delete_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proovedores',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
