# Generated by Django 5.2.6 on 2025-09-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0003_alter_proovedores_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proovedores',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
