# Generated by Django 5.2.6 on 2025-10-02 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0006_remove_pasillo_disponible_remove_planta_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasillo',
            name='plnata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genstionalmacen.planta'),
        ),
    ]
