# Generated by Django 5.2.6 on 2025-10-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0008_rename_plnata_pasillo_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='catidad_maxima',
            field=models.IntegerField(default=3),
        ),
    ]
