# Generated by Django 5.2.6 on 2025-10-02 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0011_remove_pasillo_planta_planta_pasillo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='pasillo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genstionalmacen.pasillo'),
        ),
    ]
