# Generated by Django 5.2.6 on 2025-10-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0012_alter_planta_pasillo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='secciones_maximas',
            field=models.IntegerField(default=3),
        ),
    ]
