# Generated by Django 5.2.6 on 2025-10-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0020_alter_secciones_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genstionalmacen.secciones'),
        ),
    ]
