# Generated by Django 5.2.6 on 2025-10-05 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0021_ubicacion_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='pasillo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantas', to='genstionalmacen.pasillo'),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='codigo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='genstionalmacen.planta'),
        ),
    ]
