# Generated by Django 5.2.6 on 2025-10-06 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0022_alter_planta_pasillo_alter_secciones_codigo_and_more'),
    ]

    operations = [
    ]
