# Generated by Django 5.2.6 on 2025-10-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0002_rename_models'),
        ('genstionalmacen', '0023_auto_20251006_1738'),
    ]

    operations = [
    ]
