# Generated by Django 5.2.6 on 2025-10-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genstionalmacen', '0026_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genstionalmacen.ubicaciones'),
        ),
    ]
